[package]
name = "chip8"
version = "0.1.0"
edition = "2021"


[dependencies]
bitvec = "1.0.1"
rand = "0.8.5"
sdl2= { version =  "0.35.2"}
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html